// ============================================================================
// AIDT — AI Authorship Heuristics
// ============================================================================
// Heuristic 1: PR description signature match (weight 0.3)
// Heuristic 2: Diff entropy score (weight 0.5)
// Heuristic 3: Copilot metrics API acceptance rate (weight 0.2, opt-in)
// ============================================================================

import type { PrFile } from "./types.js";

// ---------------------------------------------------------------------------
// Heuristic 1 — PR description signature
// ---------------------------------------------------------------------------

const AI_DESCRIPTION_PATTERNS = [
  /generated by copilot/i,
  /co-authored-by: github-actions/i,
  /co-authored-by: copilot/i,
  /claude suggested/i,
  /cursor generated/i,
  /ai-generated/i,
];

export function computeDescriptionMatch(title: string, body: string): boolean {
  const text = `${title}\n${body}`;
  return AI_DESCRIPTION_PATTERNS.some((pattern) => pattern.test(text));
}

// ---------------------------------------------------------------------------
// Heuristic 2 — Diff entropy
// ---------------------------------------------------------------------------

const LINE_LENGTH_VARIANCE_BASELINE = 15;
const INDENT_VARIANCE_BASELINE = 2;

function variance(values: number[]): number {
  if (values.length < 2) {
    return 0;
  }
  const mean = values.reduce((s, v) => s + v, 0) / values.length;
  return values.reduce((s, v) => s + (v - mean) ** 2, 0) / values.length;
}

function indentDepth(line: string): number {
  let depth = 0;
  for (const ch of line) {
    if (ch === "\t") {
      depth += 1;
    } else if (ch === " ") {
      depth += 0.25; // 4 spaces = 1 tab unit
    } else {
      break;
    }
  }
  return depth;
}

function isSubstantiveLine(line: string): boolean {
  const trimmed = line.trimStart();
  if (trimmed.length === 0) {
    return false;
  }
  // Filter comment-only lines
  if (/^(\/\/|#|\*|\/\*)/.test(trimmed)) {
    return false;
  }
  return true;
}

function scoreFilePatch(patch: string): number {
  const addedLines = patch
    .split("\n")
    .filter((l) => l.startsWith("+") && !l.startsWith("+++"))
    .map((l) => l.slice(1)) // strip leading '+'
    .filter(isSubstantiveLine);

  if (addedLines.length < 3) {
    return 0;
  }

  const lengths = addedLines.map((l) => l.length);
  const indents = addedLines.map(indentDepth);

  const lenVar = variance(lengths);
  const indVar = variance(indents);

  const normLen = Math.min(1, lenVar / LINE_LENGTH_VARIANCE_BASELINE);
  const normInd = Math.min(1, indVar / INDENT_VARIANCE_BASELINE);

  const combinedVariance = (normLen + normInd) / 2;
  return Math.max(0, 1 - combinedVariance);
}

/** Compute the PR-level diff entropy score weighted by lines changed per file. */
export function computeDiffEntropyScore(files: PrFile[]): number {
  const candidates = files.filter((f) => f.patch && f.changes > 0);
  if (candidates.length === 0) {
    return 0;
  }

  let weightedSum = 0;
  let totalLines = 0;

  for (const file of candidates) {
    const score = scoreFilePatch(file.patch!);
    weightedSum += score * file.changes;
    totalLines += file.changes;
  }

  return totalLines > 0 ? weightedSum / totalLines : 0;
}

// ---------------------------------------------------------------------------
// Heuristic 3 — Copilot metrics API acceptance rate
// ---------------------------------------------------------------------------

interface CopilotMetricDay {
  date: string;
  total_suggestions_count?: number;
  total_acceptances_count?: number;
}

/** Fetch Copilot org-level acceptance rate for the window around the PR merge date. */
export async function fetchCopilotAcceptanceRate(
  org: string,
  mergedAt: string,
  copilotToken: string,
): Promise<number | null> {
  try {
    const mergeDate = new Date(mergedAt);
    const since = new Date(mergeDate);
    since.setDate(since.getDate() - 7);
    const until = new Date(mergeDate);
    until.setDate(until.getDate() + 1);

    const url =
      `https://api.github.com/orgs/${encodeURIComponent(org)}/copilot/metrics` +
      `?since=${since.toISOString().slice(0, 10)}&until=${until.toISOString().slice(0, 10)}`;

    const res = await fetch(url, {
      headers: {
        Authorization: `Bearer ${copilotToken}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
    });

    if (!res.ok) {
      return null;
    }

    const data = (await res.json()) as CopilotMetricDay[];
    if (!Array.isArray(data) || data.length === 0) {
      return null;
    }

    const totalSuggestions = data.reduce((s, d) => s + (d.total_suggestions_count ?? 0), 0);
    const totalAcceptances = data.reduce((s, d) => s + (d.total_acceptances_count ?? 0), 0);

    if (totalSuggestions === 0) {
      return null;
    }
    return totalAcceptances / totalSuggestions;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Combined authorship score
// ---------------------------------------------------------------------------

/**
 * Combine the three heuristics into a single AI authorship percentage.
 * If h3 is null, redistribute its weight proportionally to h1 and h2.
 */
export function computeAiAuthorshipPct(
  h1Match: boolean,
  h2Score: number,
  h3Rate: number | null,
): number {
  const h1 = h1Match ? 1.0 : 0.0;

  if (h3Rate === null) {
    // Redistribute 0.2 weight proportionally: h1 gets 0.3/0.8 of total, h2 gets 0.5/0.8
    return h1 * (0.3 / 0.8) + h2Score * (0.5 / 0.8);
  }

  return h1 * 0.3 + h2Score * 0.5 + h3Rate * 0.2;
}
