import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import {
  computeDescriptionMatch,
  computeDiffEntropyScore,
  computeAiAuthorshipPct,
  fetchCopilotAcceptanceRate,
} from "../authorship";
import type { PrFile } from "../types";

// ---------------------------------------------------------------------------
// Heuristic 1 — description signature
// ---------------------------------------------------------------------------

describe("computeDescriptionMatch", () => {
  it("returns true for 'generated by copilot' in body", () => {
    expect(computeDescriptionMatch("fix: something", "This was Generated by Copilot")).toBe(true);
  });

  it("returns true for 'co-authored-by: copilot' in body", () => {
    expect(computeDescriptionMatch("fix", "Co-Authored-By: Copilot\nsome other text")).toBe(true);
  });

  it("returns true for 'ai-generated' in title", () => {
    expect(computeDescriptionMatch("AI-Generated refactor", "")).toBe(true);
  });

  it("returns true for 'claude suggested' in body", () => {
    expect(computeDescriptionMatch("refactor", "Claude Suggested this approach")).toBe(true);
  });

  it("returns true for 'cursor generated' in body", () => {
    expect(computeDescriptionMatch("feat", "Cursor Generated this code block")).toBe(true);
  });

  it("returns true for 'co-authored-by: github-actions'", () => {
    expect(computeDescriptionMatch("chore", "Co-Authored-By: github-actions[bot]")).toBe(true);
  });

  it("returns false for a normal human-written PR", () => {
    expect(
      computeDescriptionMatch(
        "fix: correct off-by-one error in pagination",
        "Found this while investigating issue #42. The loop was starting at 1 instead of 0.",
      ),
    ).toBe(false);
  });

  it("returns false for empty title and body", () => {
    expect(computeDescriptionMatch("", "")).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Heuristic 2 — diff entropy scoring
// ---------------------------------------------------------------------------

const REGULAR_DIFF_FILE: PrFile = {
  filename: "src/utils.ts",
  additions: 10,
  deletions: 0,
  changes: 10,
  // Highly regular: identical line lengths, uniform indentation — AI signature
  patch: `@@ -0,0 +1,10 @@
+function alpha() {
+  return "value";
+}
+function beta() {
+  return "value";
+}
+function gamma() {
+  return "value";
+}
+function delta() {`,
};

const IRREGULAR_DIFF_FILE: PrFile = {
  filename: "src/processor.ts",
  additions: 8,
  deletions: 0,
  changes: 8,
  // Highly irregular: wildly varying line lengths and indentation depths
  patch: `@@ -0,0 +1,8 @@
+x = 1;
+            const veryLongVariableNameThatExceedsNormalConventionsByALargeFactor = someExtremelyVerboseFunctionCallWithManyParameters(argOne, argTwo, argThree);
+  y = 2;
+                                    z = deeply.nested.call.chain.that.goes.on.for.a.very.long.time.indeed();
+a = 3;
+    b = someFunc();
+c = 4;
+                d = anotherVeryLongStatement();`,
};

describe("computeDiffEntropyScore", () => {
  it("returns a score in [0, 1] for any input", () => {
    const score = computeDiffEntropyScore([REGULAR_DIFF_FILE, IRREGULAR_DIFF_FILE]);
    expect(score).toBeGreaterThanOrEqual(0);
    expect(score).toBeLessThanOrEqual(1);
  });

  it("scores regular (AI-like) diffs higher than irregular (human-like) diffs", () => {
    const regularScore = computeDiffEntropyScore([REGULAR_DIFF_FILE]);
    const irregularScore = computeDiffEntropyScore([IRREGULAR_DIFF_FILE]);
    expect(regularScore).toBeGreaterThan(irregularScore);
  });

  it("returns 0 for empty file list", () => {
    expect(computeDiffEntropyScore([])).toBe(0);
  });

  it("returns 0 for files without patches", () => {
    const noPatch: PrFile = { filename: "binary.png", additions: 0, deletions: 0, changes: 5 };
    expect(computeDiffEntropyScore([noPatch])).toBe(0);
  });

  it("weighs files by lines changed", () => {
    // A very small change (1 line) and a large change (100 lines) — the large one dominates
    const smallFile: PrFile = {
      filename: "tiny.ts",
      additions: 1,
      deletions: 0,
      changes: 1,
      patch: `@@ -0,0 +1 @@\n+x = 1;`,
    };
    const largeRegularFile: PrFile = {
      ...REGULAR_DIFF_FILE,
      changes: 100,
    };
    const score = computeDiffEntropyScore([smallFile, largeRegularFile]);
    const regularOnly = computeDiffEntropyScore([largeRegularFile]);
    // Should be close to the large regular file's score
    expect(Math.abs(score - regularOnly)).toBeLessThan(0.3);
  });
});

// ---------------------------------------------------------------------------
// Heuristic 3 — Copilot acceptance rate (fetch mock)
// ---------------------------------------------------------------------------

describe("fetchCopilotAcceptanceRate", () => {
  beforeEach(() => {
    vi.stubGlobal("fetch", vi.fn());
  });

  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("returns acceptance rate when API succeeds", async () => {
    const mockFetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => [
        { date: "2026-01-01", total_suggestions_count: 100, total_acceptances_count: 35 },
        { date: "2026-01-02", total_suggestions_count: 80, total_acceptances_count: 28 },
      ],
    });
    vi.stubGlobal("fetch", mockFetch);

    const result = await fetchCopilotAcceptanceRate("myorg", "2026-01-03T10:00:00Z", "ghp_token");
    // (35+28) / (100+80) = 63/180 ≈ 0.35
    expect(result).not.toBeNull();
    expect(result!).toBeCloseTo(63 / 180, 3);
  });

  it("returns null when API returns non-200", async () => {
    vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: false, status: 403 }));
    const result = await fetchCopilotAcceptanceRate("myorg", "2026-01-03T10:00:00Z", "ghp_token");
    expect(result).toBeNull();
  });

  it("returns null when API returns empty array", async () => {
    vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: true, json: async () => [] }));
    const result = await fetchCopilotAcceptanceRate("myorg", "2026-01-03T10:00:00Z", "ghp_token");
    expect(result).toBeNull();
  });

  it("returns null when fetch throws", async () => {
    vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new Error("network error")));
    const result = await fetchCopilotAcceptanceRate("myorg", "2026-01-03T10:00:00Z", "ghp_token");
    expect(result).toBeNull();
  });

  it("returns null when total_suggestions_count is 0", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        json: async () => [
          { date: "2026-01-01", total_suggestions_count: 0, total_acceptances_count: 0 },
        ],
      }),
    );
    const result = await fetchCopilotAcceptanceRate("myorg", "2026-01-03T10:00:00Z", "ghp_token");
    expect(result).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Combined authorship score
// ---------------------------------------------------------------------------

describe("computeAiAuthorshipPct", () => {
  it("uses weights 0.3/0.5/0.2 when h3 is available", () => {
    const score = computeAiAuthorshipPct(true, 0.5, 0.4);
    // 1.0*0.3 + 0.5*0.5 + 0.4*0.2 = 0.3 + 0.25 + 0.08 = 0.63
    expect(score).toBeCloseTo(0.63, 5);
  });

  it("redistributes h3 weight proportionally when h3 is null", () => {
    const score = computeAiAuthorshipPct(true, 0.5, null);
    // h1 weight = 0.3/0.8, h2 weight = 0.5/0.8
    // 1.0*(0.3/0.8) + 0.5*(0.5/0.8) = 0.375 + 0.3125 = 0.6875
    expect(score).toBeCloseTo(0.6875, 5);
  });

  it("returns 0 when all signals are zero and h3 is null", () => {
    expect(computeAiAuthorshipPct(false, 0.0, null)).toBe(0.0);
  });

  it("returns 0 when all signals are zero and h3 is zero", () => {
    expect(computeAiAuthorshipPct(false, 0.0, 0.0)).toBe(0.0);
  });

  it("returns 1.0 when all signals are maximum (h3 available)", () => {
    expect(computeAiAuthorshipPct(true, 1.0, 1.0)).toBeCloseTo(1.0, 5);
  });

  it("returns 1.0 when all signals are maximum (h3 null)", () => {
    expect(computeAiAuthorshipPct(true, 1.0, null)).toBeCloseTo(1.0, 5);
  });
});
