import { describe, it, expect, vi } from "vitest";
import { computeBaselineDensity } from "../baseline";
import { BASELINE_FALLBACK } from "../scorer";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeMergedPr(num: number, daysAgo: number, title = "fix: routine patch", body = "") {
  const merged = new Date();
  merged.setDate(merged.getDate() - daysAgo);
  const created = new Date(merged);
  created.setHours(created.getHours() - 2); // created 2h before merge
  return {
    number: num,
    title,
    body,
    state: "closed",
    merged_at: merged.toISOString(),
    created_at: created.toISOString(),
  };
}

function makeReviews(prCreatedAt: string, reviewOffsetHours: number) {
  const submitted = new Date(prCreatedAt);
  submitted.setHours(submitted.getHours() + reviewOffsetHours);
  return [{ state: "APPROVED", submitted_at: submitted.toISOString() }];
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("computeBaselineDensity", () => {
  it("falls back to 6.0 when fewer than 10 qualifying PRs", async () => {
    // Return 5 eligible PRs — not enough for baseline
    const mockOctokit = {
      pulls: {
        list: vi.fn().mockResolvedValue({
          data: Array.from({ length: 5 }, (_, i) => makeMergedPr(i + 2, 10)),
        }),
        listReviews: vi.fn().mockResolvedValue({ data: [] }),
        listFiles: vi.fn().mockResolvedValue({ data: [{ changes: 20 }] }),
      },
    };

    const result = await computeBaselineDensity(mockOctokit as never, "owner", "repo", 1);
    expect(result.density).toBe(BASELINE_FALLBACK);
    expect(result.source).toBe("fallback");
  });

  it("computes median density when ≥10 qualifying PRs exist", async () => {
    // 12 PRs, each with 1h of review time and 100 lines changed → 3600/100 = 36 s/line
    const prs = Array.from({ length: 12 }, (_, i) => makeMergedPr(i + 2, 5 + i));

    const mockOctokit = {
      pulls: {
        list: vi.fn().mockResolvedValue({ data: prs }),
        listReviews: vi.fn().mockImplementation(({ pull_number }: { pull_number: number }) => {
          const pr = prs.find((p) => p.number === pull_number)!;
          return Promise.resolve({ data: makeReviews(pr.created_at, 1) }); // 1h review
        }),
        listFiles: vi.fn().mockResolvedValue({ data: [{ changes: 100 }] }),
      },
    };

    const result = await computeBaselineDensity(mockOctokit as never, "owner", "repo", 1);
    expect(result.source).toBe("computed");
    // 1h = 3600s, 100 lines → 36s/line
    expect(result.density).toBeCloseTo(36, 0);
  });

  it("excludes the target PR number from baseline candidates", async () => {
    const targetPr = makeMergedPr(1, 1); // PR #1 — the one being analyzed
    const otherPrs = Array.from({ length: 12 }, (_, i) => makeMergedPr(i + 2, 5 + i));

    const mockOctokit = {
      pulls: {
        list: vi.fn().mockResolvedValue({ data: [targetPr, ...otherPrs] }),
        listReviews: vi.fn().mockImplementation(({ pull_number }: { pull_number: number }) => {
          const prs = [targetPr, ...otherPrs];
          const pr = prs.find((p) => p.number === pull_number)!;
          return Promise.resolve({ data: makeReviews(pr.created_at, 1) });
        }),
        listFiles: vi.fn().mockResolvedValue({ data: [{ changes: 100 }] }),
      },
    };

    const result = await computeBaselineDensity(mockOctokit as never, "owner", "repo", 1);
    expect(result.source).toBe("computed");
    // Verify target PR was not included — listReviews should not be called for PR #1
    const callArgs = (mockOctokit.pulls.listReviews as ReturnType<typeof vi.fn>).mock.calls;
    const calledPrNumbers = callArgs.map(
      (c: unknown[]) => (c[0] as { pull_number: number }).pull_number,
    );
    expect(calledPrNumbers).not.toContain(1);
  });

  it("excludes PRs with AI description signals from baseline", async () => {
    const aiPrs = Array.from({ length: 12 }, (_, i) =>
      makeMergedPr(i + 2, 5, "Generated by Copilot"),
    );
    const mockOctokit = {
      pulls: {
        list: vi.fn().mockResolvedValue({ data: aiPrs }),
        listReviews: vi.fn().mockResolvedValue({ data: [] }),
        listFiles: vi.fn().mockResolvedValue({ data: [{ changes: 50 }] }),
      },
    };

    const result = await computeBaselineDensity(mockOctokit as never, "owner", "repo", 1);
    expect(result.density).toBe(BASELINE_FALLBACK);
    expect(result.source).toBe("fallback");
  });

  it("excludes PRs with high diff entropy (likely AI) from baseline even without description signal", async () => {
    // Patch with perfectly uniform lines — zero variance → entropy score of 1.0 → above ENTROPY_AI_THRESHOLD
    const uniformPatch = Array.from({ length: 20 }, (_, i) => `+const x${i} = getValue();`).join(
      "\n",
    );
    const aiLikeFiles = [{ changes: 20, patch: uniformPatch }];

    const prs = Array.from({ length: 12 }, (_, i) => makeMergedPr(i + 2, 5 + i));
    const mockOctokit = {
      pulls: {
        list: vi.fn().mockResolvedValue({ data: prs }),
        listReviews: vi.fn().mockImplementation(({ pull_number }: { pull_number: number }) => {
          const pr = prs.find((p) => p.number === pull_number)!;
          return Promise.resolve({ data: makeReviews(pr.created_at, 1) });
        }),
        listFiles: vi.fn().mockResolvedValue({ data: aiLikeFiles }),
      },
    };

    const result = await computeBaselineDensity(mockOctokit as never, "owner", "repo", 1);
    expect(result.density).toBe(BASELINE_FALLBACK);
    expect(result.source).toBe("fallback");
  });

  it("falls back to 6.0 when qualifying PRs have no reviews", async () => {
    // 12 PRs with no reviews → no density values collected → < 10 densities
    const prs = Array.from({ length: 12 }, (_, i) => makeMergedPr(i + 2, 5 + i));
    const mockOctokit = {
      pulls: {
        list: vi.fn().mockResolvedValue({ data: prs }),
        listReviews: vi.fn().mockResolvedValue({ data: [] }), // no reviews
        listFiles: vi.fn().mockResolvedValue({ data: [{ changes: 50 }] }),
      },
    };

    const result = await computeBaselineDensity(mockOctokit as never, "owner", "repo", 1);
    expect(result.density).toBe(BASELINE_FALLBACK);
    expect(result.source).toBe("fallback");
  });
});
